# NumPy

In [42]:
# Create an Array
import numpy as np

array1 = np.array([1,2,3]) # One dimension (1x3)

array2 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]]) # Three dimensions (3x3)

array3 = np.arange(0,11,2) # Start,stop,step

array4 = np.linspace(0,5,10) # One dimensional array consisting of 10 values between 0-5

array5 = np.random.randn(5,5) # 5x5 Matrix with random normal distributed numbers from 0-1

array6 = np.zeros(shape=(3,4)) # Rows, columns

array7 = np.random.choice(10,(3,4)) # Creates a 3X4 matrix with random values between 0 and 9


array7

array([[7, 7, 2, 7],
       [0, 7, 2, 5],
       [9, 4, 1, 2]])

In [68]:
# Slicing
import numpy as np

array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12],
                  [13,14,15]])

array[1,1] # Row, Column (starts at 0)
array[1:3:1] # Start (Inclusive):Stop (Not Inclusive):Step

array([[4, 5, 6],
       [7, 8, 9]])

In [72]:
# Filter
import numpy as np

array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12],
                  [13,14,15]])

array[array > 6]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [87]:
# Update
import numpy as np

array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

array[1,1] = 6

array

array([[1, 2, 3],
       [4, 6, 6],
       [7, 8, 9]])

In [88]:
# Shape
import numpy as np

array = np.array([[1,2,3],
                  [4,5,6]])

array.shape

(2, 3)

In [89]:
# Reshape
import numpy as np

array = np.array([[1,2,3],
                  [4,5,6]])

array.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
# Sum, Max, Min, Len
import numpy as np

array = np.array([[1,2,3],
                  [4,5,6]])

array + 100 # Adds 100 to every value in array
array.max()
array.min()
array.sum()
array.sum(axis=0) # Get sum of each column (axis=0) or row (axis=1)


array([5, 7, 9])

In [106]:
# Add, Multiply, Divide Arrays
import numpy as np

array1 = np.array([[1,2,3],
                  [4,5,6]])

array2 = np.array([[7,8,9],
                  [10,11,12]])

array1 + array2
array1 * array2
array1 / array2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [113]:
# Find Index (argwhere,argmax,argmin)
import numpy as np

array = np.array([[1,2,3],
                  [4,5,6]])

array.argmax() # Returns Index of Max Value
array.argmin() # Returns Index of Min Value
np.argwhere(array == 2) # Returns Row,Column Index

array([[0, 1]])

In [114]:
# Create Identity Matrix
import numpy as np

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])